### ISSUE TITLE
module 'hashids' has no attribute 'encode' - Python 3.6.3

### ISSUE THREAD

**Issue by themsay** [davidaurelio/hashids-python#24]
Hi,
I found this interesting but testing on `Python 3.6.3` result to error below.

```
> cd /tmp
> python3 -m venv env
> . env/bin/activate
(env) > pip install hashids
Collecting hashids
  Using cached hashids-1.2.0.tar.gz
Installing collected packages: hashids
  Running setup.py install for hashids ... done
Successfully installed hashids-1.2.0

(env) > python
Python 3.6.3 (default, Oct  4 2017, 06:09:15) 
[GCC 4.2.1 Compatible Apple LLVM 9.0.0 (clang-900.0.37)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>>
>>> import hashids
>>>
>>> hashid = hashids.encode(123)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
AttributeError: module 'hashids' has no attribute 'encode'
>>>
>>> ints = hashids.decode('xoz')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
AttributeError: module 'hashids' has no attribute 'decode'
>>>
```
Any idea on how to resolve this? Thanks in advance.

**Comment by carltongibson** [comment]
The usage from the README is this: 

```
from hashids import Hashids  
hashids = Hashids()                 
```

**Comment by themsay** [comment]
@carltongibson thanks for pointing that out.
